//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About Page</summary>
	[PublishedModel("aboutPage")]
	public partial class AboutPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "aboutPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<AboutPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// About Us Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutUsImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutUsImage");

		///<summary>
		/// About Us Image Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsImageText")]
		public virtual string AboutUsImageText => this.Value<string>(_publishedValueFallback, "aboutUsImageText");

		///<summary>
		/// About Us Quote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsQuote")]
		public virtual string AboutUsQuote => this.Value<string>(_publishedValueFallback, "aboutUsQuote");

		///<summary>
		/// About Us Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText1")]
		public virtual string AboutUsText1 => this.Value<string>(_publishedValueFallback, "aboutUsText1");

		///<summary>
		/// About Us Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText2")]
		public virtual string AboutUsText2 => this.Value<string>(_publishedValueFallback, "aboutUsText2");

		///<summary>
		/// About Us Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText3")]
		public virtual string AboutUsText3 => this.Value<string>(_publishedValueFallback, "aboutUsText3");

		///<summary>
		/// About Us Text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText4")]
		public virtual string AboutUsText4 => this.Value<string>(_publishedValueFallback, "aboutUsText4");

		///<summary>
		/// About Us Text5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText5")]
		public virtual string AboutUsText5 => this.Value<string>(_publishedValueFallback, "aboutUsText5");

		///<summary>
		/// About Us Text6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText6")]
		public virtual string AboutUsText6 => this.Value<string>(_publishedValueFallback, "aboutUsText6");

		///<summary>
		/// About Us Text7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText7")]
		public virtual string AboutUsText7 => this.Value<string>(_publishedValueFallback, "aboutUsText7");

		///<summary>
		/// Next Project Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectHeadline")]
		public virtual string NextProjectHeadline => this.Value<string>(_publishedValueFallback, "nextProjectHeadline");

		///<summary>
		/// Next Project Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImage");

		///<summary>
		/// Next Project Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageAlt")]
		public virtual string NextProjectImageAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageAlt");

		///<summary>
		/// Next Project Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImageBehind");

		///<summary>
		/// Next Project Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehindAlt")]
		public virtual string NextProjectImageBehindAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageBehindAlt");

		///<summary>
		/// Next Project Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText")]
		public virtual string NextProjectText => this.Value<string>(_publishedValueFallback, "nextProjectText");

		///<summary>
		/// Next Project Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText2")]
		public virtual string NextProjectText2 => this.Value<string>(_publishedValueFallback, "nextProjectText2");

		///<summary>
		/// Next Project Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText3")]
		public virtual string NextProjectText3 => this.Value<string>(_publishedValueFallback, "nextProjectText3");

		///<summary>
		/// Next Project Text Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline")]
		public virtual string NextProjectTextHeadline => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline");

		///<summary>
		/// Next Project Text Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline2")]
		public virtual string NextProjectTextHeadline2 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline2");

		///<summary>
		/// Next Project Text Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline3")]
		public virtual string NextProjectTextHeadline3 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline3");

		///<summary>
		/// Review Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewHeadline")]
		public virtual string ReviewHeadline => this.Value<string>(_publishedValueFallback, "reviewHeadline");

		///<summary>
		/// Review Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewImage");

		///<summary>
		/// Review Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewImageAlt")]
		public virtual string ReviewImageAlt => this.Value<string>(_publishedValueFallback, "reviewImageAlt");

		///<summary>
		/// Review Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewName")]
		public virtual string ReviewName => this.Value<string>(_publishedValueFallback, "reviewName");

		///<summary>
		/// Review Name2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewName2")]
		public virtual string ReviewName2 => this.Value<string>(_publishedValueFallback, "reviewName2");

		///<summary>
		/// Review Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewText")]
		public virtual string ReviewText => this.Value<string>(_publishedValueFallback, "reviewText");

		///<summary>
		/// Review Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewTitle")]
		public virtual string ReviewTitle => this.Value<string>(_publishedValueFallback, "reviewTitle");

		///<summary>
		/// Tab Location Headline1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tabLocationHeadline1")]
		public virtual string TabLocationHeadline1 => this.Value<string>(_publishedValueFallback, "tabLocationHeadline1");

		///<summary>
		/// Tab Location Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tabLocationHeadline2")]
		public virtual string TabLocationHeadline2 => this.Value<string>(_publishedValueFallback, "tabLocationHeadline2");

		///<summary>
		/// Tab Location Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tabLocationTitle")]
		public virtual string TabLocationTitle => this.Value<string>(_publishedValueFallback, "tabLocationTitle");

		///<summary>
		/// Team Card1 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard1Headline")]
		public virtual string TeamCard1Headline => this.Value<string>(_publishedValueFallback, "teamCard1Headline");

		///<summary>
		/// Team Card1 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard1Image");

		///<summary>
		/// Team Card1 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard1ImageAlt")]
		public virtual string TeamCard1ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard1ImageAlt");

		///<summary>
		/// Team Card1 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard1Text")]
		public virtual string TeamCard1Text => this.Value<string>(_publishedValueFallback, "teamCard1Text");

		///<summary>
		/// Team Card2 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard2Headline")]
		public virtual string TeamCard2Headline => this.Value<string>(_publishedValueFallback, "teamCard2Headline");

		///<summary>
		/// Team Card2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard2Image");

		///<summary>
		/// Team Card2 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard2ImageAlt")]
		public virtual string TeamCard2ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard2ImageAlt");

		///<summary>
		/// Team Card2 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard2Text")]
		public virtual string TeamCard2Text => this.Value<string>(_publishedValueFallback, "teamCard2Text");

		///<summary>
		/// Team Card3 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard3Headline")]
		public virtual string TeamCard3Headline => this.Value<string>(_publishedValueFallback, "teamCard3Headline");

		///<summary>
		/// Team Card3 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard3Image");

		///<summary>
		/// Team Card3 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard3ImageAlt")]
		public virtual string TeamCard3ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard3ImageAlt");

		///<summary>
		/// Team Card3 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard3Text")]
		public virtual string TeamCard3Text => this.Value<string>(_publishedValueFallback, "teamCard3Text");

		///<summary>
		/// Team Card4 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard4Headline")]
		public virtual string TeamCard4Headline => this.Value<string>(_publishedValueFallback, "teamCard4Headline");

		///<summary>
		/// Team Card4 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard4Image");

		///<summary>
		/// Team Card4 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard4ImageAlt")]
		public virtual string TeamCard4ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard4ImageAlt");

		///<summary>
		/// Team Card4 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard4Text")]
		public virtual string TeamCard4Text => this.Value<string>(_publishedValueFallback, "teamCard4Text");

		///<summary>
		/// Team Card5 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard5Headline")]
		public virtual string TeamCard5Headline => this.Value<string>(_publishedValueFallback, "teamCard5Headline");

		///<summary>
		/// Team Card5 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard5Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard5Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard5Image");

		///<summary>
		/// Team Card5 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard5ImageAlt")]
		public virtual string TeamCard5ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard5ImageAlt");

		///<summary>
		/// Team Card5 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard5Text")]
		public virtual string TeamCard5Text => this.Value<string>(_publishedValueFallback, "teamCard5Text");

		///<summary>
		/// Team Card6 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard6Headline")]
		public virtual string TeamCard6Headline => this.Value<string>(_publishedValueFallback, "teamCard6Headline");

		///<summary>
		/// Team Card6 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard6Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard6Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard6Image");

		///<summary>
		/// Team Card6Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard6ImageAlt")]
		public virtual string TeamCard6ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard6ImageAlt");

		///<summary>
		/// Team Card6 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard6Text")]
		public virtual string TeamCard6Text => this.Value<string>(_publishedValueFallback, "teamCard6Text");

		///<summary>
		/// Team Card7 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard7Headline")]
		public virtual string TeamCard7Headline => this.Value<string>(_publishedValueFallback, "teamCard7Headline");

		///<summary>
		/// Team Card7 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard7Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamCard7Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamCard7Image");

		///<summary>
		/// Team Card7 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard7ImageAlt")]
		public virtual string TeamCard7ImageAlt => this.Value<string>(_publishedValueFallback, "teamCard7ImageAlt");

		///<summary>
		/// Team Card7 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamCard7Text")]
		public virtual string TeamCard7Text => this.Value<string>(_publishedValueFallback, "teamCard7Text");

		///<summary>
		/// Team Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamHeadline")]
		public virtual string TeamHeadline => this.Value<string>(_publishedValueFallback, "teamHeadline");

		///<summary>
		/// Team Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamTitle")]
		public virtual string TeamTitle => this.Value<string>(_publishedValueFallback, "teamTitle");
	}
}
