//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Contact</summary>
	[PublishedModel("contact")]
	public partial class Contact : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "contact";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<Contact, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Contact(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Call Back Form Btn Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackFormBtnText")]
		public virtual string CallBackFormBtnText => this.Value<string>(_publishedValueFallback, "callBackFormBtnText");

		///<summary>
		/// Call Back Form Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackFormText1")]
		public virtual string CallBackFormText1 => this.Value<string>(_publishedValueFallback, "callBackFormText1");

		///<summary>
		/// Call Back Form Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackFormText2")]
		public virtual string CallBackFormText2 => this.Value<string>(_publishedValueFallback, "callBackFormText2");

		///<summary>
		/// Call Back Form Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackFormText3")]
		public virtual string CallBackFormText3 => this.Value<string>(_publishedValueFallback, "callBackFormText3");

		///<summary>
		/// Call Back Form Text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackFormText4")]
		public virtual string CallBackFormText4 => this.Value<string>(_publishedValueFallback, "callBackFormText4");

		///<summary>
		/// Call Back Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackHeadline")]
		public virtual string CallBackHeadline => this.Value<string>(_publishedValueFallback, "callBackHeadline");

		///<summary>
		/// Call Back Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackText")]
		public virtual string CallBackText => this.Value<string>(_publishedValueFallback, "callBackText");

		///<summary>
		/// Call Back Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("callBackTitle")]
		public virtual string CallBackTitle => this.Value<string>(_publishedValueFallback, "callBackTitle");

		///<summary>
		/// Contact Map
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactMap")]
		public virtual string ContactMap => this.Value<string>(_publishedValueFallback, "contactMap");

		///<summary>
		/// Contact Tab Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactTabHeadline")]
		public virtual string ContactTabHeadline => this.Value<string>(_publishedValueFallback, "contactTabHeadline");

		///<summary>
		/// Contact Tab Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactTabText1")]
		public virtual string ContactTabText1 => this.Value<string>(_publishedValueFallback, "contactTabText1");

		///<summary>
		/// Contact Tab Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactTabText2")]
		public virtual string ContactTabText2 => this.Value<string>(_publishedValueFallback, "contactTabText2");

		///<summary>
		/// Next Project Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectHeadline")]
		public virtual string NextProjectHeadline => this.Value<string>(_publishedValueFallback, "nextProjectHeadline");

		///<summary>
		/// Next Project Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImage");

		///<summary>
		/// Next Project Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageAlt")]
		public virtual string NextProjectImageAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageAlt");

		///<summary>
		/// Next Project Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImageBehind");

		///<summary>
		/// Next Project Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehindAlt")]
		public virtual string NextProjectImageBehindAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageBehindAlt");

		///<summary>
		/// Next Project Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText")]
		public virtual string NextProjectText => this.Value<string>(_publishedValueFallback, "nextProjectText");

		///<summary>
		/// Next Project Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText2")]
		public virtual string NextProjectText2 => this.Value<string>(_publishedValueFallback, "nextProjectText2");

		///<summary>
		/// Next Project Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText3")]
		public virtual string NextProjectText3 => this.Value<string>(_publishedValueFallback, "nextProjectText3");

		///<summary>
		/// Next Project Text Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline")]
		public virtual string NextProjectTextHeadline => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline");

		///<summary>
		/// Next Project Text Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline2")]
		public virtual string NextProjectTextHeadline2 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline2");

		///<summary>
		/// Next Project Text Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline3")]
		public virtual string NextProjectTextHeadline3 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline3");

		///<summary>
		/// Recent Project Company1 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany1Image");

		///<summary>
		/// Recent Project Company2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany2Image");

		///<summary>
		/// Recent Project Company3 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany3Image");

		///<summary>
		/// Recent Project Company4 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany4Image");

		///<summary>
		/// Recent Project Company5 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany5Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany5Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany5Image");

		///<summary>
		/// Recent Project Company6 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany6Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany6Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany6Image");

		///<summary>
		/// Recent Project Company Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompanyAlt")]
		public virtual string RecentProjectCompanyAlt => this.Value<string>(_publishedValueFallback, "recentProjectCompanyAlt");
	}
}
