//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Home Page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// About Call Btn Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallBtnText")]
		public virtual string AboutCallBtnText => this.Value<string>(_publishedValueFallback, "aboutCallBtnText");

		///<summary>
		/// About Call Form Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallFormEmail")]
		public virtual string AboutCallFormEmail => this.Value<string>(_publishedValueFallback, "aboutCallFormEmail");

		///<summary>
		/// About Call Form Job
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallFormJob")]
		public virtual string AboutCallFormJob => this.Value<string>(_publishedValueFallback, "aboutCallFormJob");

		///<summary>
		/// About Call Form Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallFormName")]
		public virtual string AboutCallFormName => this.Value<string>(_publishedValueFallback, "aboutCallFormName");

		///<summary>
		/// About Call Form Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallFormPhone")]
		public virtual string AboutCallFormPhone => this.Value<string>(_publishedValueFallback, "aboutCallFormPhone");

		///<summary>
		/// About Call Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallHeadline")]
		public virtual string AboutCallHeadline => this.Value<string>(_publishedValueFallback, "aboutCallHeadline");

		///<summary>
		/// About Call Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutCallText")]
		public virtual string AboutCallText => this.Value<string>(_publishedValueFallback, "aboutCallText");

		///<summary>
		/// About - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSectionTitle")]
		public virtual string AboutSectionTitle => this.Value<string>(_publishedValueFallback, "aboutSectionTitle");

		///<summary>
		/// About Signature
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSignature")]
		public virtual string AboutSignature => this.Value<string>(_publishedValueFallback, "aboutSignature");

		///<summary>
		/// About Signature Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSignatureImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutSignatureImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutSignatureImage");

		///<summary>
		/// About Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsHeadline")]
		public virtual string AboutUsHeadline => this.Value<string>(_publishedValueFallback, "aboutUsHeadline");

		///<summary>
		/// About Quote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsQuote")]
		public virtual string AboutUsQuote => this.Value<string>(_publishedValueFallback, "aboutUsQuote");

		///<summary>
		/// About Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText")]
		public virtual string AboutUsText => this.Value<string>(_publishedValueFallback, "aboutUsText");

		///<summary>
		/// Hero - Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeroBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "heroBackgroundImage");

		///<summary>
		/// Hero - Btn Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroBtnText")]
		public virtual string HeroBtnText => this.Value<string>(_publishedValueFallback, "heroBtnText");

		///<summary>
		/// Hero - Btn Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroBtnUrl")]
		public virtual string HeroBtnUrl => this.Value<string>(_publishedValueFallback, "heroBtnUrl");

		///<summary>
		/// Hero - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroHeadline")]
		public virtual string HeroHeadline => this.Value<string>(_publishedValueFallback, "heroHeadline");

		///<summary>
		/// Hero - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroText")]
		public virtual string HeroText => this.Value<string>(_publishedValueFallback, "heroText");

		///<summary>
		/// Recent Project Card1 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard1Headline")]
		public virtual string RecentProjectCard1Headline => this.Value<string>(_publishedValueFallback, "recentProjectCard1Headline");

		///<summary>
		/// Recent Project Card1 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCard1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCard1Image");

		///<summary>
		/// Recent Project Card1 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard1ImageAlt")]
		public virtual string RecentProjectCard1ImageAlt => this.Value<string>(_publishedValueFallback, "recentProjectCard1ImageAlt");

		///<summary>
		/// Recent Project Card1 Image Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard1ImageUrl")]
		public virtual string RecentProjectCard1ImageUrl => this.Value<string>(_publishedValueFallback, "recentProjectCard1ImageUrl");

		///<summary>
		/// Recent Project Card1 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard1Text")]
		public virtual string RecentProjectCard1Text => this.Value<string>(_publishedValueFallback, "recentProjectCard1Text");

		///<summary>
		/// Recent Project Card1 Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard1Url")]
		public virtual string RecentProjectCard1Url => this.Value<string>(_publishedValueFallback, "recentProjectCard1Url");

		///<summary>
		/// Recent Project Card2 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard2Headline")]
		public virtual string RecentProjectCard2Headline => this.Value<string>(_publishedValueFallback, "recentProjectCard2Headline");

		///<summary>
		/// Recent Project Card2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCard2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCard2Image");

		///<summary>
		/// Recent Project Card2 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard2ImageAlt")]
		public virtual string RecentProjectCard2ImageAlt => this.Value<string>(_publishedValueFallback, "recentProjectCard2ImageAlt");

		///<summary>
		/// Recent Project Card2 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard2Text")]
		public virtual string RecentProjectCard2Text => this.Value<string>(_publishedValueFallback, "recentProjectCard2Text");

		///<summary>
		/// Recent Project Card3 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard3Headline")]
		public virtual string RecentProjectCard3Headline => this.Value<string>(_publishedValueFallback, "recentProjectCard3Headline");

		///<summary>
		/// Recent Project Card3 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCard3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCard3Image");

		///<summary>
		/// Recent Project Card3 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard3ImageAlt")]
		public virtual string RecentProjectCard3ImageAlt => this.Value<string>(_publishedValueFallback, "recentProjectCard3ImageAlt");

		///<summary>
		/// Recent Project Card3 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard3Text")]
		public virtual string RecentProjectCard3Text => this.Value<string>(_publishedValueFallback, "recentProjectCard3Text");

		///<summary>
		/// Recent Project Card4 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard4Headline")]
		public virtual string RecentProjectCard4Headline => this.Value<string>(_publishedValueFallback, "recentProjectCard4Headline");

		///<summary>
		/// Recent Project Card4 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCard4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCard4Image");

		///<summary>
		/// Recent Project Card4 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard4ImageAlt")]
		public virtual string RecentProjectCard4ImageAlt => this.Value<string>(_publishedValueFallback, "recentProjectCard4ImageAlt");

		///<summary>
		/// Recent Project Card4 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCard4Text")]
		public virtual string RecentProjectCard4Text => this.Value<string>(_publishedValueFallback, "recentProjectCard4Text");

		///<summary>
		/// Recent Project Company1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany1");

		///<summary>
		/// Recent Project Company2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany2Image");

		///<summary>
		/// Recent Project Company3 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany3Image");

		///<summary>
		/// Recent Project Company4 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany4Image");

		///<summary>
		/// Recent Project Company5 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany5Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany5Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany5Image");

		///<summary>
		/// Recent Project Company6 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompany6Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentProjectCompany6Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "recentProjectCompany6Image");

		///<summary>
		/// Recent Project Company Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectCompanyAlt")]
		public virtual string RecentProjectCompanyAlt => this.Value<string>(_publishedValueFallback, "recentProjectCompanyAlt");

		///<summary>
		/// Recent Project Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectHeadline")]
		public virtual string RecentProjectHeadline => this.Value<string>(_publishedValueFallback, "recentProjectHeadline");

		///<summary>
		/// Recent Project Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentProjectTitle")]
		public virtual string RecentProjectTitle => this.Value<string>(_publishedValueFallback, "recentProjectTitle");

		///<summary>
		/// Service Card1 headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard1Headline")]
		public virtual string ServiceCard1Headline => this.Value<string>(_publishedValueFallback, "serviceCard1Headline");

		///<summary>
		/// Service Card1 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCard1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCard1Image");

		///<summary>
		/// Service Card1 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard1ImageAlt")]
		public virtual string ServiceCard1ImageAlt => this.Value<string>(_publishedValueFallback, "serviceCard1ImageAlt");

		///<summary>
		/// Service Card1 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard1Text")]
		public virtual string ServiceCard1Text => this.Value<string>(_publishedValueFallback, "serviceCard1Text");

		///<summary>
		/// Service Card1 Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard1Url")]
		public virtual string ServiceCard1Url => this.Value<string>(_publishedValueFallback, "serviceCard1Url");

		///<summary>
		/// Service Card2 headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard2Headline")]
		public virtual string ServiceCard2Headline => this.Value<string>(_publishedValueFallback, "serviceCard2Headline");

		///<summary>
		/// Service Card2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCard2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCard2Image");

		///<summary>
		/// Service Card2 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard2ImageAlt")]
		public virtual string ServiceCard2ImageAlt => this.Value<string>(_publishedValueFallback, "serviceCard2ImageAlt");

		///<summary>
		/// Service Card2 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard2Text")]
		public virtual string ServiceCard2Text => this.Value<string>(_publishedValueFallback, "serviceCard2Text");

		///<summary>
		/// Service Card3 headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard3Headline")]
		public virtual string ServiceCard3Headline => this.Value<string>(_publishedValueFallback, "serviceCard3Headline");

		///<summary>
		/// Service Card3 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCard3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCard3Image");

		///<summary>
		/// Service Card3 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard3ImageAlt")]
		public virtual string ServiceCard3ImageAlt => this.Value<string>(_publishedValueFallback, "serviceCard3ImageAlt");

		///<summary>
		/// Service Card3 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard3Text")]
		public virtual string ServiceCard3Text => this.Value<string>(_publishedValueFallback, "serviceCard3Text");

		///<summary>
		/// Service Card4 headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard4Headline")]
		public virtual string ServiceCard4Headline => this.Value<string>(_publishedValueFallback, "serviceCard4Headline");

		///<summary>
		/// Service Card4 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCard4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCard4Image");

		///<summary>
		/// Service Card4 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard4ImageAlt")]
		public virtual string ServiceCard4ImageAlt => this.Value<string>(_publishedValueFallback, "serviceCard4ImageAlt");

		///<summary>
		/// Service Card4 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard4Text")]
		public virtual string ServiceCard4Text => this.Value<string>(_publishedValueFallback, "serviceCard4Text");

		///<summary>
		/// Service Card5 headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard5Headline")]
		public virtual string ServiceCard5Headline => this.Value<string>(_publishedValueFallback, "serviceCard5Headline");

		///<summary>
		/// Service Card5 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard5Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCard5Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCard5Image");

		///<summary>
		/// Service Card5 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard5ImageAlt")]
		public virtual string ServiceCard5ImageAlt => this.Value<string>(_publishedValueFallback, "serviceCard5ImageAlt");

		///<summary>
		/// Service Card5 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard5Text")]
		public virtual string ServiceCard5Text => this.Value<string>(_publishedValueFallback, "serviceCard5Text");

		///<summary>
		/// Service Card6 headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard6Headline")]
		public virtual string ServiceCard6Headline => this.Value<string>(_publishedValueFallback, "serviceCard6Headline");

		///<summary>
		/// Service Card6 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard6Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCard6Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCard6Image");

		///<summary>
		/// Service Card6 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard6ImageAlt")]
		public virtual string ServiceCard6ImageAlt => this.Value<string>(_publishedValueFallback, "serviceCard6ImageAlt");

		///<summary>
		/// Service Card6 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCard6Text")]
		public virtual string ServiceCard6Text => this.Value<string>(_publishedValueFallback, "serviceCard6Text");

		///<summary>
		/// Service Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceHeadline")]
		public virtual string ServiceHeadline => this.Value<string>(_publishedValueFallback, "serviceHeadline");

		///<summary>
		/// Service Label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceLabel")]
		public virtual string ServiceLabel => this.Value<string>(_publishedValueFallback, "serviceLabel");

		///<summary>
		/// Success Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SuccessBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "successBackgroundImage");

		///<summary>
		/// Success Background Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBackgroundImageAlt")]
		public virtual string SuccessBackgroundImageAlt => this.Value<string>(_publishedValueFallback, "successBackgroundImageAlt");

		///<summary>
		/// Success Background Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBackgroundImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SuccessBackgroundImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "successBackgroundImageBehind");

		///<summary>
		/// Success Background Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBackgroundImageBehindAlt")]
		public virtual string SuccessBackgroundImageBehindAlt => this.Value<string>(_publishedValueFallback, "successBackgroundImageBehindAlt");

		///<summary>
		/// Success Card1 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successCard1Headline")]
		public virtual string SuccessCard1Headline => this.Value<string>(_publishedValueFallback, "successCard1Headline");

		///<summary>
		/// Success Card1 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successCard1Text")]
		public virtual string SuccessCard1Text => this.Value<string>(_publishedValueFallback, "successCard1Text");

		///<summary>
		/// Success Card2 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successCard2Headline")]
		public virtual string SuccessCard2Headline => this.Value<string>(_publishedValueFallback, "successCard2Headline");

		///<summary>
		/// Success Card2 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successCard2Text")]
		public virtual string SuccessCard2Text => this.Value<string>(_publishedValueFallback, "successCard2Text");

		///<summary>
		/// Success Card3 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successCard3Headline")]
		public virtual string SuccessCard3Headline => this.Value<string>(_publishedValueFallback, "successCard3Headline");

		///<summary>
		/// Success Card3 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successCard3Text")]
		public virtual string SuccessCard3Text => this.Value<string>(_publishedValueFallback, "successCard3Text");

		///<summary>
		/// Success Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successHeadline")]
		public virtual string SuccessHeadline => this.Value<string>(_publishedValueFallback, "successHeadline");

		///<summary>
		/// Success Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successTitle")]
		public virtual string SuccessTitle => this.Value<string>(_publishedValueFallback, "successTitle");

		///<summary>
		/// Trust Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TrustBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "trustBackgroundImage");

		///<summary>
		/// Trust Background Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustBackgroundImageAlt")]
		public virtual string TrustBackgroundImageAlt => this.Value<string>(_publishedValueFallback, "trustBackgroundImageAlt");

		///<summary>
		/// Trust Background Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustBackgroundImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TrustBackgroundImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "trustBackgroundImageBehind");

		///<summary>
		/// Trust Background Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustBackgroundImageBehindAlt")]
		public virtual string TrustBackgroundImageBehindAlt => this.Value<string>(_publishedValueFallback, "trustBackgroundImageBehindAlt");

		///<summary>
		/// Trust Btn Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustBtnText")]
		public virtual string TrustBtnText => this.Value<string>(_publishedValueFallback, "trustBtnText");

		///<summary>
		/// Trust Headline1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustHeadline1")]
		public virtual string TrustHeadline1 => this.Value<string>(_publishedValueFallback, "trustHeadline1");

		///<summary>
		/// Trust Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustHeadline2")]
		public virtual string TrustHeadline2 => this.Value<string>(_publishedValueFallback, "trustHeadline2");

		///<summary>
		/// Trust Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trustText")]
		public virtual string TrustText => this.Value<string>(_publishedValueFallback, "trustText");
	}
}
