//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Juva-Inc</summary>
	[PublishedModel("juvaInc")]
	public partial class JuvaInc : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "juvaInc";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<JuvaInc, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public JuvaInc(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("date")]
		public virtual string Date => this.Value<string>(_publishedValueFallback, "date");

		///<summary>
		/// Headline1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline1")]
		public virtual string Headline1 => this.Value<string>(_publishedValueFallback, "headline1");

		///<summary>
		/// Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline2")]
		public virtual string Headline2 => this.Value<string>(_publishedValueFallback, "headline2");

		///<summary>
		/// Headline2 Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline2Text1")]
		public virtual string Headline2Text1 => this.Value<string>(_publishedValueFallback, "headline2Text1");

		///<summary>
		/// Headline2 Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline2Text2")]
		public virtual string Headline2Text2 => this.Value<string>(_publishedValueFallback, "headline2Text2");

		///<summary>
		/// Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline3")]
		public virtual string Headline3 => this.Value<string>(_publishedValueFallback, "headline3");

		///<summary>
		/// Headline3 Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline3Text1")]
		public virtual string Headline3Text1 => this.Value<string>(_publishedValueFallback, "headline3Text1");

		///<summary>
		/// Headline3 Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline3Text2")]
		public virtual string Headline3Text2 => this.Value<string>(_publishedValueFallback, "headline3Text2");

		///<summary>
		/// Headline3 Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline3Text3")]
		public virtual string Headline3Text3 => this.Value<string>(_publishedValueFallback, "headline3Text3");

		///<summary>
		/// Headline4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline4")]
		public virtual string Headline4 => this.Value<string>(_publishedValueFallback, "headline4");

		///<summary>
		/// Headline4 Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline4Text1")]
		public virtual string Headline4Text1 => this.Value<string>(_publishedValueFallback, "headline4Text1");

		///<summary>
		/// Headline4 Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline4Text2")]
		public virtual string Headline4Text2 => this.Value<string>(_publishedValueFallback, "headline4Text2");

		///<summary>
		/// Help Form Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("helpFormText")]
		public virtual string HelpFormText => this.Value<string>(_publishedValueFallback, "helpFormText");

		///<summary>
		/// Help Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("helpHeadline")]
		public virtual string HelpHeadline => this.Value<string>(_publishedValueFallback, "helpHeadline");

		///<summary>
		/// Help Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("helpText")]
		public virtual string HelpText => this.Value<string>(_publishedValueFallback, "helpText");

		///<summary>
		/// Juva Image1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops JuvaImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "juvaImage1");

		///<summary>
		/// Juva Image1 Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaImage1Alt")]
		public virtual string JuvaImage1Alt => this.Value<string>(_publishedValueFallback, "juvaImage1Alt");

		///<summary>
		/// Juva Image2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops JuvaImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "juvaImage2");

		///<summary>
		/// Juva Image2 Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaImage2Alt")]
		public virtual string JuvaImage2Alt => this.Value<string>(_publishedValueFallback, "juvaImage2Alt");

		///<summary>
		/// Juva Image3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops JuvaImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "juvaImage3");

		///<summary>
		/// Juva Image3 Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaImage3Alt")]
		public virtual string JuvaImage3Alt => this.Value<string>(_publishedValueFallback, "juvaImage3Alt");

		///<summary>
		/// Juva Tab Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaTabHeadline")]
		public virtual string JuvaTabHeadline => this.Value<string>(_publishedValueFallback, "juvaTabHeadline");

		///<summary>
		/// Juva Tab Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaTabText1")]
		public virtual string JuvaTabText1 => this.Value<string>(_publishedValueFallback, "juvaTabText1");

		///<summary>
		/// Juva Tab Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaTabText2")]
		public virtual string JuvaTabText2 => this.Value<string>(_publishedValueFallback, "juvaTabText2");

		///<summary>
		/// Juva Tab Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("juvaTabText3")]
		public virtual string JuvaTabText3 => this.Value<string>(_publishedValueFallback, "juvaTabText3");

		///<summary>
		/// Key Note Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyNoteText1")]
		public virtual string KeyNoteText1 => this.Value<string>(_publishedValueFallback, "keyNoteText1");

		///<summary>
		/// Key Note Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyNoteText2")]
		public virtual string KeyNoteText2 => this.Value<string>(_publishedValueFallback, "keyNoteText2");

		///<summary>
		/// Key Note Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keyNoteText3")]
		public virtual string KeyNoteText3 => this.Value<string>(_publishedValueFallback, "keyNoteText3");

		///<summary>
		/// Next Project Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectHeadline")]
		public virtual string NextProjectHeadline => this.Value<string>(_publishedValueFallback, "nextProjectHeadline");

		///<summary>
		/// Next Project Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImage");

		///<summary>
		/// Next Project Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageAlt")]
		public virtual string NextProjectImageAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageAlt");

		///<summary>
		/// Next Project Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImageBehind");

		///<summary>
		/// Next Project Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehindAlt")]
		public virtual string NextProjectImageBehindAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageBehindAlt");

		///<summary>
		/// Next Project Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText")]
		public virtual string NextProjectText => this.Value<string>(_publishedValueFallback, "nextProjectText");

		///<summary>
		/// Next Project Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText2")]
		public virtual string NextProjectText2 => this.Value<string>(_publishedValueFallback, "nextProjectText2");

		///<summary>
		/// Next Project Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText3")]
		public virtual string NextProjectText3 => this.Value<string>(_publishedValueFallback, "nextProjectText3");

		///<summary>
		/// Next Project Text Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline")]
		public virtual string NextProjectTextHeadline => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline");

		///<summary>
		/// Next Project Text Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline2")]
		public virtual string NextProjectTextHeadline2 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline2");

		///<summary>
		/// Next Project Text Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline3")]
		public virtual string NextProjectTextHeadline3 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline3");

		///<summary>
		/// Small Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallHeadline")]
		public virtual string SmallHeadline => this.Value<string>(_publishedValueFallback, "smallHeadline");

		///<summary>
		/// Tag Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagHeadline")]
		public virtual string TagHeadline => this.Value<string>(_publishedValueFallback, "tagHeadline");

		///<summary>
		/// Tags Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsHeadline")]
		public virtual string TagsHeadline => this.Value<string>(_publishedValueFallback, "tagsHeadline");

		///<summary>
		/// Tags Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText1")]
		public virtual string TagsText1 => this.Value<string>(_publishedValueFallback, "tagsText1");

		///<summary>
		/// Tags Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText2")]
		public virtual string TagsText2 => this.Value<string>(_publishedValueFallback, "tagsText2");

		///<summary>
		/// Tags Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText3")]
		public virtual string TagsText3 => this.Value<string>(_publishedValueFallback, "tagsText3");

		///<summary>
		/// Tags Text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText4")]
		public virtual string TagsText4 => this.Value<string>(_publishedValueFallback, "tagsText4");

		///<summary>
		/// Tags Text5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText5")]
		public virtual string TagsText5 => this.Value<string>(_publishedValueFallback, "tagsText5");

		///<summary>
		/// Tags Text6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText6")]
		public virtual string TagsText6 => this.Value<string>(_publishedValueFallback, "tagsText6");

		///<summary>
		/// Tags Text7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText7")]
		public virtual string TagsText7 => this.Value<string>(_publishedValueFallback, "tagsText7");

		///<summary>
		/// Tags Text8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagsText8")]
		public virtual string TagsText8 => this.Value<string>(_publishedValueFallback, "tagsText8");

		///<summary>
		/// Tag Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText1")]
		public virtual string TagText1 => this.Value<string>(_publishedValueFallback, "tagText1");

		///<summary>
		/// Tag Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText2")]
		public virtual string TagText2 => this.Value<string>(_publishedValueFallback, "tagText2");

		///<summary>
		/// Tag Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText3")]
		public virtual string TagText3 => this.Value<string>(_publishedValueFallback, "tagText3");
	}
}
