//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Projects Page</summary>
	[PublishedModel("projects")]
	public partial class Projects : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "projects";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<Projects, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Projects(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Help Form Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("helpFormText")]
		public virtual string HelpFormText => this.Value<string>(_publishedValueFallback, "helpFormText");

		///<summary>
		/// Help Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("helpHeadline")]
		public virtual string HelpHeadline => this.Value<string>(_publishedValueFallback, "helpHeadline");

		///<summary>
		/// Help Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("helpText")]
		public virtual string HelpText => this.Value<string>(_publishedValueFallback, "helpText");

		///<summary>
		/// Next Project Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectHeadline")]
		public virtual string NextProjectHeadline => this.Value<string>(_publishedValueFallback, "nextProjectHeadline");

		///<summary>
		/// Next Project Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImage");

		///<summary>
		/// Next Project Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageAlt")]
		public virtual string NextProjectImageAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageAlt");

		///<summary>
		/// Next Project Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImageBehind");

		///<summary>
		/// Next Project Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehindAlt")]
		public virtual string NextProjectImageBehindAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageBehindAlt");

		///<summary>
		/// Next Project Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText")]
		public virtual string NextProjectText => this.Value<string>(_publishedValueFallback, "nextProjectText");

		///<summary>
		/// Next Project Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText2")]
		public virtual string NextProjectText2 => this.Value<string>(_publishedValueFallback, "nextProjectText2");

		///<summary>
		/// Next Project Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText3")]
		public virtual string NextProjectText3 => this.Value<string>(_publishedValueFallback, "nextProjectText3");

		///<summary>
		/// Next Project Text Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline")]
		public virtual string NextProjectTextHeadline => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline");

		///<summary>
		/// Next Project Text Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline2")]
		public virtual string NextProjectTextHeadline2 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline2");

		///<summary>
		/// Next Project Text Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline3")]
		public virtual string NextProjectTextHeadline3 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline3");

		///<summary>
		/// Project Card1 Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1Date")]
		public virtual string ProjectCard1Date => this.Value<string>(_publishedValueFallback, "projectCard1Date");

		///<summary>
		/// Project Card1 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1Headline")]
		public virtual string ProjectCard1Headline => this.Value<string>(_publishedValueFallback, "projectCard1Headline");

		///<summary>
		/// Project Card1 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCard1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCard1Image");

		///<summary>
		/// Project Card1 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1ImageAlt")]
		public virtual string ProjectCard1ImageAlt => this.Value<string>(_publishedValueFallback, "projectCard1ImageAlt");

		///<summary>
		/// Project Card1 Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1LinkText")]
		public virtual string ProjectCard1LinkText => this.Value<string>(_publishedValueFallback, "projectCard1LinkText");

		///<summary>
		/// Project Card1 Link Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1LinkUrl")]
		public virtual string ProjectCard1LinkUrl => this.Value<string>(_publishedValueFallback, "projectCard1LinkUrl");

		///<summary>
		/// Project Card1 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard1Text")]
		public virtual string ProjectCard1Text => this.Value<string>(_publishedValueFallback, "projectCard1Text");

		///<summary>
		/// Project Card2 Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard2Date")]
		public virtual string ProjectCard2Date => this.Value<string>(_publishedValueFallback, "projectCard2Date");

		///<summary>
		/// Project Card2 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard2Headline")]
		public virtual string ProjectCard2Headline => this.Value<string>(_publishedValueFallback, "projectCard2Headline");

		///<summary>
		/// Project Card2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCard2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCard2Image");

		///<summary>
		/// Project Card2 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard2ImageAlt")]
		public virtual string ProjectCard2ImageAlt => this.Value<string>(_publishedValueFallback, "projectCard2ImageAlt");

		///<summary>
		/// Project Card2 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard2Text")]
		public virtual string ProjectCard2Text => this.Value<string>(_publishedValueFallback, "projectCard2Text");

		///<summary>
		/// Project Card3 Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard3Date")]
		public virtual string ProjectCard3Date => this.Value<string>(_publishedValueFallback, "projectCard3Date");

		///<summary>
		/// Project Card3 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard3Headline")]
		public virtual string ProjectCard3Headline => this.Value<string>(_publishedValueFallback, "projectCard3Headline");

		///<summary>
		/// Project Card3 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCard3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCard3Image");

		///<summary>
		/// Project Card3 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard3ImageAlt")]
		public virtual string ProjectCard3ImageAlt => this.Value<string>(_publishedValueFallback, "projectCard3ImageAlt");

		///<summary>
		/// Project Card3 Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard3Text")]
		public virtual string ProjectCard3Text => this.Value<string>(_publishedValueFallback, "projectCard3Text");

		///<summary>
		/// Project Card4 Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard4Date")]
		public virtual string ProjectCard4Date => this.Value<string>(_publishedValueFallback, "projectCard4Date");

		///<summary>
		/// Project Card4 Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard4Headline")]
		public virtual string ProjectCard4Headline => this.Value<string>(_publishedValueFallback, "projectCard4Headline");

		///<summary>
		/// Project Card4 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCard4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCard4Image");

		///<summary>
		/// Project Card4 Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard4ImageAlt")]
		public virtual string ProjectCard4ImageAlt => this.Value<string>(_publishedValueFallback, "projectCard4ImageAlt");

		///<summary>
		/// Project Card4Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCard4Text")]
		public virtual string ProjectCard4Text => this.Value<string>(_publishedValueFallback, "projectCard4Text");

		///<summary>
		/// Projects Tab Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsTabHeadline")]
		public virtual string ProjectsTabHeadline => this.Value<string>(_publishedValueFallback, "projectsTabHeadline");

		///<summary>
		/// Projects Tab Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsTabText1")]
		public virtual string ProjectsTabText1 => this.Value<string>(_publishedValueFallback, "projectsTabText1");

		///<summary>
		/// Projects Tab Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsTabText2")]
		public virtual string ProjectsTabText2 => this.Value<string>(_publishedValueFallback, "projectsTabText2");

		///<summary>
		/// Services Tab Change Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesTabChangeText1")]
		public virtual string ServicesTabChangeText1 => this.Value<string>(_publishedValueFallback, "servicesTabChangeText1");

		///<summary>
		/// Services Tab Change Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesTabChangeText2")]
		public virtual string ServicesTabChangeText2 => this.Value<string>(_publishedValueFallback, "servicesTabChangeText2");

		///<summary>
		/// Services Tab Change Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesTabChangeText3")]
		public virtual string ServicesTabChangeText3 => this.Value<string>(_publishedValueFallback, "servicesTabChangeText3");

		///<summary>
		/// Services Tab Change Text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesTabChangeText4")]
		public virtual string ServicesTabChangeText4 => this.Value<string>(_publishedValueFallback, "servicesTabChangeText4");

		///<summary>
		/// Tag Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagHeadline")]
		public virtual string TagHeadline => this.Value<string>(_publishedValueFallback, "tagHeadline");

		///<summary>
		/// Tag Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText1")]
		public virtual string TagText1 => this.Value<string>(_publishedValueFallback, "tagText1");

		///<summary>
		/// Tag Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText2")]
		public virtual string TagText2 => this.Value<string>(_publishedValueFallback, "tagText2");

		///<summary>
		/// Tag Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText3")]
		public virtual string TagText3 => this.Value<string>(_publishedValueFallback, "tagText3");

		///<summary>
		/// Tag Text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText4")]
		public virtual string TagText4 => this.Value<string>(_publishedValueFallback, "tagText4");

		///<summary>
		/// Tag Text5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText5")]
		public virtual string TagText5 => this.Value<string>(_publishedValueFallback, "tagText5");

		///<summary>
		/// Tag Text6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText6")]
		public virtual string TagText6 => this.Value<string>(_publishedValueFallback, "tagText6");

		///<summary>
		/// Tag Text7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText7")]
		public virtual string TagText7 => this.Value<string>(_publishedValueFallback, "tagText7");

		///<summary>
		/// Tag Text8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagText8")]
		public virtual string TagText8 => this.Value<string>(_publishedValueFallback, "tagText8");
	}
}
