//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Risk Management</summary>
	[PublishedModel("riskManagement")]
	public partial class RiskManagement : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "riskManagement";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<RiskManagement, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public RiskManagement(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Next Project Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectHeadline")]
		public virtual string NextProjectHeadline => this.Value<string>(_publishedValueFallback, "nextProjectHeadline");

		///<summary>
		/// Next Project Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImage");

		///<summary>
		/// Next Project Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageAlt")]
		public virtual string NextProjectImageAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageAlt");

		///<summary>
		/// Next Project Image Behind
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehind")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops NextProjectImageBehind => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "nextProjectImageBehind");

		///<summary>
		/// Next Project Image Behind Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectImageBehindAlt")]
		public virtual string NextProjectImageBehindAlt => this.Value<string>(_publishedValueFallback, "nextProjectImageBehindAlt");

		///<summary>
		/// Next Project Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText")]
		public virtual string NextProjectText => this.Value<string>(_publishedValueFallback, "nextProjectText");

		///<summary>
		/// Next Project Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText2")]
		public virtual string NextProjectText2 => this.Value<string>(_publishedValueFallback, "nextProjectText2");

		///<summary>
		/// Next Project Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectText3")]
		public virtual string NextProjectText3 => this.Value<string>(_publishedValueFallback, "nextProjectText3");

		///<summary>
		/// Next Project Text Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline")]
		public virtual string NextProjectTextHeadline => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline");

		///<summary>
		/// Next Project Text Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline2")]
		public virtual string NextProjectTextHeadline2 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline2");

		///<summary>
		/// Next Project Text Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextProjectTextHeadline3")]
		public virtual string NextProjectTextHeadline3 => this.Value<string>(_publishedValueFallback, "nextProjectTextHeadline3");

		///<summary>
		/// Question Btn Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("questionBtnText")]
		public virtual string QuestionBtnText => this.Value<string>(_publishedValueFallback, "questionBtnText");

		///<summary>
		/// Question Form Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("questionFormText1")]
		public virtual string QuestionFormText1 => this.Value<string>(_publishedValueFallback, "questionFormText1");

		///<summary>
		/// Question Form Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("questionFormText2")]
		public virtual string QuestionFormText2 => this.Value<string>(_publishedValueFallback, "questionFormText2");

		///<summary>
		/// Question Form Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("questionFormText3")]
		public virtual string QuestionFormText3 => this.Value<string>(_publishedValueFallback, "questionFormText3");

		///<summary>
		/// Question Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("questionHeadline")]
		public virtual string QuestionHeadline => this.Value<string>(_publishedValueFallback, "questionHeadline");

		///<summary>
		/// Risk Management Content Left Form Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftFormText")]
		public virtual string RiskManagementContentLeftFormText => this.Value<string>(_publishedValueFallback, "riskManagementContentLeftFormText");

		///<summary>
		/// Risk Management Content Left Headline1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftHeadline1")]
		public virtual string RiskManagementContentLeftHeadline1 => this.Value<string>(_publishedValueFallback, "riskManagementContentLeftHeadline1");

		///<summary>
		/// Risk Management Content Left Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftHeadline2")]
		public virtual string RiskManagementContentLeftHeadline2 => this.Value<string>(_publishedValueFallback, "riskManagementContentLeftHeadline2");

		///<summary>
		/// Risk Management Content Left Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RiskManagementContentLeftImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "riskManagementContentLeftImage");

		///<summary>
		/// Risk Management Content Left Image Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftImageAlt")]
		public virtual string RiskManagementContentLeftImageAlt => this.Value<string>(_publishedValueFallback, "riskManagementContentLeftImageAlt");

		///<summary>
		/// Risk Management Content Left Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftText")]
		public virtual string RiskManagementContentLeftText => this.Value<string>(_publishedValueFallback, "riskManagementContentLeftText");

		///<summary>
		/// Risk Management Content Left Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentLeftText2")]
		public virtual string RiskManagementContentLeftText2 => this.Value<string>(_publishedValueFallback, "riskManagementContentLeftText2");

		///<summary>
		/// Risk Management Content Right Headline1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline1")]
		public virtual string RiskManagementContentRightHeadline1 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline1");

		///<summary>
		/// Risk Management Content Right Headline2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2")]
		public virtual string RiskManagementContentRightHeadline2 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2");

		///<summary>
		/// Risk Management Content Right Headline2 Key Note1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2KeyNote1")]
		public virtual string RiskManagementContentRightHeadline2KeyNote1 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2KeyNote1");

		///<summary>
		/// Risk Management Content Right Headline2 Key Note2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2KeyNote2")]
		public virtual string RiskManagementContentRightHeadline2KeyNote2 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2KeyNote2");

		///<summary>
		/// Risk Management Content Right Headline2 Key Note3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2KeyNote3")]
		public virtual string RiskManagementContentRightHeadline2KeyNote3 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2KeyNote3");

		///<summary>
		/// Risk Management Content Right Headline2 Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2Text1")]
		public virtual string RiskManagementContentRightHeadline2Text1 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2Text1");

		///<summary>
		/// Risk Management Content Right Headline2 Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2Text2")]
		public virtual string RiskManagementContentRightHeadline2Text2 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2Text2");

		///<summary>
		/// Risk Management Content Right Headline2 Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2Text3")]
		public virtual string RiskManagementContentRightHeadline2Text3 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2Text3");

		///<summary>
		/// Risk Management Content Right Headline2 Text4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2Text4")]
		public virtual string RiskManagementContentRightHeadline2Text4 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2Text4");

		///<summary>
		/// Risk Management Content Right Headline2 Text5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline2Text5")]
		public virtual string RiskManagementContentRightHeadline2Text5 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline2Text5");

		///<summary>
		/// Risk Management Content Right Headline3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline3")]
		public virtual string RiskManagementContentRightHeadline3 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline3");

		///<summary>
		/// Risk Management Content Right Headline3 Key Note1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline3KeyNote1")]
		public virtual string RiskManagementContentRightHeadline3KeyNote1 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline3KeyNote1");

		///<summary>
		/// Risk Management Content Right Headline3 Key Note2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline3KeyNote2")]
		public virtual string RiskManagementContentRightHeadline3KeyNote2 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline3KeyNote2");

		///<summary>
		/// Risk Management Content Right Headline3 Key Note3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline3KeyNote3")]
		public virtual string RiskManagementContentRightHeadline3KeyNote3 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline3KeyNote3");

		///<summary>
		/// Risk Management Content Right Headline3 Key Note4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline3KeyNote4")]
		public virtual string RiskManagementContentRightHeadline3KeyNote4 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline3KeyNote4");

		///<summary>
		/// Risk Management Content Right Headline3 Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightHeadline3Text1")]
		public virtual string RiskManagementContentRightHeadline3Text1 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightHeadline3Text1");

		///<summary>
		/// Risk Management Content Right Image1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RiskManagementContentRightImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "riskManagementContentRightImage1");

		///<summary>
		/// Risk Management Content Right Image1 Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightImage1Alt")]
		public virtual string RiskManagementContentRightImage1Alt => this.Value<string>(_publishedValueFallback, "riskManagementContentRightImage1Alt");

		///<summary>
		/// Risk Management Content Right Image2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RiskManagementContentRightImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "riskManagementContentRightImage2");

		///<summary>
		/// Risk Management Content Right Image2 Alt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightImage2Alt")]
		public virtual string RiskManagementContentRightImage2Alt => this.Value<string>(_publishedValueFallback, "riskManagementContentRightImage2Alt");

		///<summary>
		/// Risk Management Content Right Key Note Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightKeyNoteText1")]
		public virtual string RiskManagementContentRightKeyNoteText1 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightKeyNoteText1");

		///<summary>
		/// Risk Management Content Right Key Note Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightKeyNoteText2")]
		public virtual string RiskManagementContentRightKeyNoteText2 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightKeyNoteText2");

		///<summary>
		/// Risk Management Content Right Key Note Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementContentRightKeyNoteText3")]
		public virtual string RiskManagementContentRightKeyNoteText3 => this.Value<string>(_publishedValueFallback, "riskManagementContentRightKeyNoteText3");

		///<summary>
		/// Risk Management Tab Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementTabHeadline")]
		public virtual string RiskManagementTabHeadline => this.Value<string>(_publishedValueFallback, "riskManagementTabHeadline");

		///<summary>
		/// Risk Management Tab Text1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementTabText1")]
		public virtual string RiskManagementTabText1 => this.Value<string>(_publishedValueFallback, "riskManagementTabText1");

		///<summary>
		/// Risk Management Tab Text2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementTabText2")]
		public virtual string RiskManagementTabText2 => this.Value<string>(_publishedValueFallback, "riskManagementTabText2");

		///<summary>
		/// Risk Management Tab Text3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("riskManagementTabText3")]
		public virtual string RiskManagementTabText3 => this.Value<string>(_publishedValueFallback, "riskManagementTabText3");
	}
}
